"""Re-fetch additional official documents used in a manual review decision."""
import re
from urllib.parse import urlsplit

from .collection import Client


def valid(rows, client=None):
    # Missing evidence is backwards compatible; an explicitly empty list is not.
    if rows is None:
        return True
    if not isinstance(rows, list) or not 1 <= len(rows) <= 5:
        return False
    from .candidate_triage import document, digest
    client = client or Client()
    for row in rows:
        if not isinstance(row, dict):
            return False
        url = row.get('url', '')
        parsed = urlsplit(url)
        if (parsed.scheme != 'https' or not parsed.hostname or parsed.username
                or parsed.password or parsed.fragment
                or not re.fullmatch(r'[a-f0-9]{64}', row.get('content_sha256', ''))
                or not row.get('reviewed_at') or not row.get('rationale')):
            return False
        quotes = row.get('quotes')
        if not isinstance(quotes, list) or not quotes or not all(isinstance(q, str) and q.strip() for q in quotes):
            return False
        # These are explicit reviewer-approved URLs, never URLs generated by AI prose.
        body, evidence = client.get(url)
        text = document(body, url)
        if (evidence['final_url'] != url or digest(text) != row['content_sha256']
                or not all(q in text for q in quotes)):
            return False
    return True
