"""
Curated Seed / Sample Dataset for Taigi Activities across Taipei, New Taipei, and Taoyuan
Sources: OPENTIX, Era Ticket, Accupass, 李江却基金會, 樂暢親子共學, 北北桃市立圖書館, FB, IG, Threads, Google Calendar
"""
from typing import List
from .models import Activity, CityEnum, CategoryEnum, SourcePlatformEnum


def get_curated_taigi_activities() -> List[Activity]:
    return [
        # =========================================================================
        # 1. 李江却台語文教基金會 (Lí Kang-khiok Taiwanese Foundation)
        # =========================================================================
        Activity(
            id="likang_lecture_01",
            title="【台語故事/講座】李江却台語文教基金會《台灣母語文化講堂：台語文學佮民間講古》",
            description="李江却基金會經典講座！邀請台語文學者深入淺出探討台語白話字、母語文學創作，並現場示範傳統民間說唱與講古藝術，適合對台語文與說故事有興趣的家長與青年。",
            city=CityEnum.TAIPEI,
            district="中正區",
            category=CategoryEnum.STORY,
            start_time="2026-09-26T14:00:00",
            end_time="2026-09-26T16:30:00",
            venue="李江却台語文教基金會 講堂 (台文通訊BONG報)",
            address="臺北市中正區青島東路5號2樓之1",
            organizer="財團法人李江却台語文教基金會",
            source_platform=SourcePlatformEnum.LI_KANG_KHIOK,
            source_url="https://www.tgb.org.tw",
            cover_image="https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=800&q=80",
            price_info="免費參加（事先線上報名）",
            is_free=True,
            tags=["李江却基金會", "台語講座", "台語講古", "台文通訊", "母語文教"]
        ),
        Activity(
            id="likang_tour_02",
            title="【台語導覽】李江却基金會《台北城內台語地名與文史散策走讀》",
            description="全台語走讀台北舊城區！跟著李江却基金會資深母語講師，從北門（承恩門）出發，探尋撫臺街洋樓、重慶南路書店街與二二八和平公園，用最地道的母語聲調講述台北城百年故事。",
            city=CityEnum.TAIPEI,
            district="中正區",
            category=CategoryEnum.TOUR,
            start_time="2026-10-10T09:00:00",
            end_time="2026-10-10T11:30:00",
            venue="台北北門廣場 (承恩門前集合)",
            address="臺北市中正區忠孝西路一段與延平北路一段路口",
            organizer="財團法人李江却台語文教基金會",
            source_platform=SourcePlatformEnum.LI_KANG_KHIOK,
            source_url="https://www.tgb.org.tw/activity_walk_taipei",
            cover_image="https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
            price_info="免費參加（限額 30 人）",
            is_free=True,
            tags=["李江却基金會", "台語導覽", "北門走讀", "文史散策", "母語文化"]
        ),

        # =========================================================================
        # 2. 樂暢親子共學 (Le-tshiòng Taigi Kids Learning)
        # =========================================================================
        Activity(
            id="lechang_picbook_01",
            title="【台語繪本】樂暢親子共學《囡仔來聽繪本・逐家歡喜講台語》新北板橋場",
            description="樂暢台語共學招牌活動！針對 2-7 歲幼兒設計的沉浸式台語繪本共讀，搭配肢體律動、台語手指謠與手作遊戲，讓孩子在自然歡樂的環境中開口說台語。",
            city=CityEnum.NEW_TAIPEI,
            district="板橋區",
            category=CategoryEnum.PICTURE_BOOK,
            start_time="2026-09-27T10:30:00",
            end_time="2026-09-27T12:00:00",
            venue="板橋 435 藝文特區 枋橋大劇院排練室",
            address="新北市板橋區中正路435號",
            organizer="樂暢親子共學團 (Le-tshiòng)",
            source_platform=SourcePlatformEnum.LE_CHANG,
            source_url="https://www.facebook.com/letshiong.taigi",
            cover_image="https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
            price_info="材料費 NT$ 250 / 組 (一大一小)",
            is_free=False,
            tags=["樂暢", "台語繪本", "親子共學", "板橋435", "幼兒共讀"]
        ),
        Activity(
            id="lechang_exp_02",
            title="【台語體驗】樂暢親子共學《大自然台語探險家：桃園大溪森林野趣手作》",
            description="全台語戶外自然探索！帶領親子走進桃園大溪林道，用台語認識花草樹木與昆蟲鳥類，並就地取材採集落葉枯枝，親手製作台語植物拓印畫與自然曼陀羅。",
            city=CityEnum.TAOYUAN,
            district="大溪區",
            category=CategoryEnum.EXPERIENCE,
            start_time="2026-10-11T13:30:00",
            end_time="2026-10-11T16:30:00",
            venue="大溪中正公園與大溪生態步道",
            address="桃園市大溪區普濟路",
            organizer="樂暢親子共學團 / 桃園母語共學小組",
            source_platform=SourcePlatformEnum.LE_CHANG,
            source_url="https://www.facebook.com/letshiong.taigi/posts/nature_exp",
            cover_image="https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
            price_info="NT$ 350 / 組 (含保險與手作教具包)",
            is_free=False,
            tags=["樂暢", "台語體驗", "大溪自然", "戶外共學", "生態探索"]
        ),

        # =========================================================================
        # 3. 北北桃公立圖書館 (Taipei / New Taipei / Taoyuan Public Libraries)
        # =========================================================================
        Activity(
            id="tpml_story_01",
            title="【台語故事】臺北市立圖書館總館《台灣母語故事屋：阿公講古予你聽》",
            description="北市圖總館定點母語推廣！特聘資深台語志工老師，以生動道具與台語童謠，為小朋友講述經典民間傳奇與台灣動物故事，歡迎闔家參與。",
            city=CityEnum.TAIPEI,
            district="大安區",
            category=CategoryEnum.STORY,
            start_time="2026-10-03T10:00:00",
            end_time="2026-10-03T11:00:00",
            venue="臺北市立圖書館總館 B1小小世界外文圖書館多功能活動室",
            address="臺北市大安區建國南路二段125號",
            organizer="臺北市立圖書館",
            source_platform=SourcePlatformEnum.LIBRARIES,
            source_url="https://tpml.gov.taipei/News_Content.aspx?n=1&s=tpml_taigi_story",
            cover_image="https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=80",
            price_info="免費入場（自由入座）",
            is_free=True,
            tags=["臺北市立圖書館", "台語故事", "母語故事屋", "北市圖總館", "親子活動"]
        ),
        Activity(
            id="ntpclib_picbook_02",
            title="【台語繪本】新北市立圖書館總館《新北愛閱讀・台語繪本樂悠遊》",
            description="新北市圖總館兒童館專場！精選教育部得獎台語繪本，帶領小朋友邊看生動大插圖邊用母語朗讀，並有繪本角色著色與台語字卡配對趣味闖關。",
            city=CityEnum.NEW_TAIPEI,
            district="板橋區",
            category=CategoryEnum.PICTURE_BOOK,
            start_time="2026-10-18T14:30:00",
            end_time="2026-10-18T15:45:00",
            venue="新北市立圖書館總館 3樓兒童閱覽區小舞台",
            address="新北市板橋區貴興路139號",
            organizer="新北市立圖書館",
            source_platform=SourcePlatformEnum.LIBRARIES,
            source_url="https://www.library.ntpc.gov.tw/singlepress/taigi_reading",
            cover_image="https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=800&q=80",
            price_info="免費入場（自由參加）",
            is_free=True,
            tags=["新北市立圖書館", "台語繪本", "新北市圖總館", "板橋", "愛閱讀"]
        ),
        Activity(
            id="tylib_story_03",
            title="【台語故事】桃園市立圖書館總館《桃林講古堂：台語童話巡演列車》",
            description="在桃園最美總圖享受台語故事時光！由桃園市台語志工劇團現場說演互動劇《桃太郎遊桃園》，結合手偶戲與全場台語問答，寓教於樂。",
            city=CityEnum.TAOYUAN,
            district="桃園區",
            category=CategoryEnum.STORY,
            start_time="2026-10-24T10:30:00",
            end_time="2026-10-24T11:45:00",
            venue="桃園市立圖書館總館 1樓微光廳",
            address="桃園市桃園區南平路303號",
            organizer="桃園市立圖書館",
            source_platform=SourcePlatformEnum.LIBRARIES,
            source_url="https://www.typl.gov.tw/zh-tw/Activity/Content/typl_taigi_drama",
            cover_image="https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=800&q=80",
            price_info="免費入場（需於官網預約劃位）",
            is_free=True,
            tags=["桃園市立圖書館", "台語故事", "桃園總圖", "微光廳", "偶戲互動"]
        ),
        Activity(
            id="tpml_tour_04",
            title="【台語導覽】臺北市立圖書館北投分館《綠建築與北投溫泉鄉台語文史走讀》",
            description="全台首座綠建築圖書館走讀！由北投文史工作者以道地台語導覽北投公園、北投溫泉博物館、地熱谷，解說日治時期北投那卡西與台語電影發源地的風華記憶。",
            city=CityEnum.TAIPEI,
            district="北投區",
            category=CategoryEnum.TOUR,
            start_time="2026-10-31T09:30:00",
            end_time="2026-10-31T12:00:00",
            venue="臺北市立圖書館北投分館 正門前廣場集合",
            address="臺北市北投區光明路251號",
            organizer="臺北市立圖書館北投分館 / 北投文史學會",
            source_platform=SourcePlatformEnum.LIBRARIES,
            source_url="https://tpml.gov.taipei/beitou_taigi_tour",
            cover_image="https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=800&q=80",
            price_info="免費參加（限額 25 名）",
            is_free=True,
            tags=["臺北市立圖書館", "北投分館", "台語導覽", "北投溫泉", "綠建築"]
        ),
        Activity(
            id="ntpclib_exp_05",
            title="【台語體驗】新北市立圖書館新店分館《傳統紅龜粿模與台語食文化手作工作坊》",
            description="帶孩子認識台灣傳統米食！全程台語教學紅龜粿「牽絲、包餡、印模」傳統工法，親手製作香甜紅豆草仔粿，並學習相關台語民俗諺語。",
            city=CityEnum.NEW_TAIPEI,
            district="新店區",
            category=CategoryEnum.EXPERIENCE,
            start_time="2026-11-08T14:00:00",
            end_time="2026-11-08T16:30:00",
            venue="新北市立圖書館新店分館 3樓多功能教室",
            address="新北市新店區北新路三段105巷2號3樓",
            organizer="新北市立圖書館新店分館",
            source_platform=SourcePlatformEnum.LIBRARIES,
            source_url="https://www.library.ntpc.gov.tw/xindian_taigi_food",
            cover_image="https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80",
            price_info="材料費 NT$ 100",
            is_free=False,
            tags=["新北市立圖書館", "新店分館", "台語體驗", "紅龜粿", "食文化"]
        ),

        # =========================================================================
        # 4. OPENTIX 兩廳院售票 (National Theater & Concert Hall)
        # =========================================================================
        Activity(
            id="opentix_taigi_play_01",
            title="【台語舞台劇】阮劇團《熱天酣眠》經典巡演台北站",
            description="改編自莎士比亞經典《仲夏夜之夢》，融入台灣常民信仰、廟會文化與生動流利的道地台語對白！全劇以台語發音，中英文字幕，笑料百出、情感真摯。",
            city=CityEnum.TAIPEI,
            district="中正區",
            category=CategoryEnum.STAGE_PLAY,
            start_time="2026-09-25T19:30:00",
            end_time="2026-09-25T21:45:00",
            venue="國家戲劇院 (National Theater)",
            address="臺北市中正區中山南路21-1號",
            organizer="阮劇團 Our Theatre",
            source_platform=SourcePlatformEnum.OPENTIX,
            source_url="https://www.opentix.life/event/18392819201",
            cover_image="https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80",
            price_info="NT$ 600 ~ 2,500 (OPENTIX 兩廳院售票)",
            is_free=False,
            tags=["台語舞台劇", "阮劇團", "國家戲劇院", "莎士比亞", "兩廳院售票"]
        ),
        Activity(
            id="opentix_puppet_08",
            title="【台語表演】台北木偶劇團《西遊記之借芭蕉扇》掌中戲大戲",
            description="國寶級掌中戲大師指導，台北木偶劇團精湛演繹！前後場鑼鼓絲竹現場伴奏，五音分明的台語說白、巧奪天工的木偶操演技巧，老少咸宜的台灣傳統偶戲極致之美。",
            city=CityEnum.NEW_TAIPEI,
            district="板橋區",
            category=CategoryEnum.PERFORMANCE,
            start_time="2026-10-17T14:30:00",
            end_time="2026-10-17T16:00:00",
            venue="新北市藝文中心 演藝廳",
            address="新北市板橋區莊敬路62號",
            organizer="台北木偶劇團 / 新北市政府文化局",
            source_platform=SourcePlatformEnum.OPENTIX,
            source_url="https://www.opentix.life/event/18392948201",
            cover_image="https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80",
            price_info="NT$ 300 ~ 800 (OPENTIX 售票)",
            is_free=False,
            tags=["布袋戲", "掌中戲", "台語表演", "新北藝文中心", "兩廳院售票"]
        ),
        Activity(
            id="opentix_play_13",
            title="【台語舞台劇】狂想劇場《阿爸的皮箱》台語原創家庭劇 桃園場",
            description="狂想劇場得獎原創舞台劇！深刻刻畫台灣戰後三代家庭的情感糾葛與語言斷層，全劇台語對話細緻入微，撼動人心，全台巡演壓軸桃園場！",
            city=CityEnum.TAOYUAN,
            district="桃園區",
            category=CategoryEnum.STAGE_PLAY,
            start_time="2026-11-07T19:30:00",
            end_time="2026-11-07T21:40:00",
            venue="桃園展演中心 展演廳",
            address="桃園市桃園區中正路1188號",
            organizer="狂想劇場 Fantasy Theatre",
            source_platform=SourcePlatformEnum.OPENTIX,
            source_url="https://www.opentix.life/event/18393019283",
            cover_image="https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80",
            price_info="NT$ 500 ~ 1,800 (OPENTIX 兩廳院售票)",
            is_free=False,
            tags=["台語舞台劇", "狂想劇場", "桃園展演中心", "家庭劇", "兩廳院售票"]
        ),

        # =========================================================================
        # 5. 年代售票 (Era Ticket)
        # =========================================================================
        Activity(
            id="eraticket_opera_02",
            title="【台語表演】明華園戲劇總團《大河彈劍》旗艦歌仔戲大作",
            description="孫翠鳳領銜主演！明華園旗艦史詩大戲，磅礴再現戰國豪情。純正台語唱腔與文武兼備的精彩打鬥，結合現代光影科技與傳統管弦樂團伴奏。",
            city=CityEnum.TAIPEI,
            district="南港區",
            category=CategoryEnum.PERFORMANCE,
            start_time="2026-10-02T19:00:00",
            end_time="2026-10-02T22:00:00",
            venue="臺北流行音樂中心 表演廳",
            address="臺北市南港區市民大道八段99號",
            organizer="明華園戲劇總團",
            source_platform=SourcePlatformEnum.ERATICKET,
            source_url="https://ticket.com.tw/application/UTK02/UTK0201_00.aspx?PRODUCT_ID=N42B8U01",
            cover_image="https://images.unsplash.com/photo-1469488865564-c2de10f69f96?auto=format&fit=crop&w=800&q=80",
            price_info="NT$ 800 ~ 3,600 (年代售票系統)",
            is_free=False,
            tags=["歌仔戲", "明華園", "台語表演", "年代售票", "孫翠鳳"]
        ),
        Activity(
            id="eraticket_perf_14",
            title="【台語表演】台灣念歌團《琴聲話當年》台語唸歌與月琴民謠音樂會",
            description="國寶級唸歌藝師同台獻藝！以大廣弦、月琴即興彈唱台灣歷史傳奇與勸世歌，原汁原味重現早期廟埕走唱藝術與優美的母語押韻聲調。",
            city=CityEnum.TAOYUAN,
            district="中壢區",
            category=CategoryEnum.PERFORMANCE,
            start_time="2026-11-14T14:30:00",
            end_time="2026-11-14T16:30:00",
            venue="中壢藝術館 音樂廳",
            address="桃園市中壢區中美路16號",
            organizer="台灣念歌團 / 桃園市政府文化局",
            source_platform=SourcePlatformEnum.ERATICKET,
            source_url="https://ticket.com.tw/application/UTK02/UTK0201_00.aspx?PRODUCT_ID=N42B9V02",
            cover_image="https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
            price_info="NT$ 300 ~ 1,000 (年代售票)",
            is_free=False,
            tags=["台語唸歌", "月琴", "台語表演", "中壢藝術館", "年代售票"]
        ),

        # =========================================================================
        # 6. Accupass 活動通
        # =========================================================================
        Activity(
            id="accupass_tour_03",
            title="【台語導覽】大稻埕百年風華・全台語文史深度走讀",
            description="「行入大稻埕，聽阮講在地故事。」由資深文史學者全程以流利優美台語導覽迪化街百年商號、霞海城隍廟、李臨秋故居及大稻埕碼頭，體驗老台北的生活美學與母語魅力。",
            city=CityEnum.TAIPEI,
            district="大同區",
            category=CategoryEnum.TOUR,
            start_time="2026-09-26T09:30:00",
            end_time="2026-09-26T12:00:00",
            venue="大稻埕遊客中心集合 (迪化街一段44號)",
            address="臺北市大同區迪化街一段44號",
            organizer="大稻埕文化工作坊 / 台灣母語聯盟",
            source_platform=SourcePlatformEnum.ACCUPASS,
            source_url="https://www.accupass.com/event/2609200832101",
            cover_image="https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=800&q=80",
            price_info="免費參加 (需事先線上報名 Accupass)",
            is_free=True,
            tags=["台語導覽", "大稻埕", "文史走讀", "迪化街", "Accupass"]
        ),
        Activity(
            id="accupass_exp_06",
            title="【台語體驗】萬華青草巷・全台語調飲與香草球手作體驗",
            description="走進百年萬華青草巷，用台語認識薄荷、魚腥草、仙草等台灣土產藥草！由在地青草達人全台語教學，親手配製客製化養生茶飲與舒壓香草球包。",
            city=CityEnum.TAIPEI,
            district="萬華區",
            category=CategoryEnum.EXPERIENCE,
            start_time="2026-10-10T14:30:00",
            end_time="2026-10-10T17:00:00",
            venue="老濟安 Healing Herbar (萬華西昌街84號)",
            address="臺北市萬華區西昌街84號",
            organizer="萬華青草復興計畫 / Accupass",
            source_platform=SourcePlatformEnum.ACCUPASS,
            source_url="https://www.accupass.com/event/2610100918231",
            cover_image="https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
            price_info="NT$ 450 (含手作材料與青草茶套餐)",
            is_free=False,
            tags=["台語體驗", "萬華青草巷", "手作工作坊", "台語生活", "Accupass"]
        ),
        Activity(
            id="accupass_tour_10",
            title="【台語導覽】淡水滬尾河港百年風雲・台語古蹟歷史散策",
            description="跟著台語文史導覽員從淡水捷運站出發，走訪紅毛城、前清淡水關稅務司官邸（小白宮）、得忌利士洋行，全台語解說滬尾戰役與開港通商的故事。",
            city=CityEnum.NEW_TAIPEI,
            district="淡水區",
            category=CategoryEnum.TOUR,
            start_time="2026-10-18T09:00:00",
            end_time="2026-10-18T12:00:00",
            venue="淡水捷運站 1號出口集合",
            address="新北市淡水區中正路1號",
            organizer="滬尾文史講堂 / Accupass",
            source_platform=SourcePlatformEnum.ACCUPASS,
            source_url="https://www.accupass.com/event/2610180847291",
            cover_image="https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
            price_info="免費參加 (限額 25 名)",
            is_free=True,
            tags=["台語導覽", "淡水", "紅毛城", "歷史走讀", "Accupass"]
        ),
        Activity(
            id="accupass_exp_12",
            title="【台語體驗】鶯歌陶瓷老街・台語手拉坯與陶藝釉彩手作工作坊",
            description="「用母語捏陶，感受泥土的溫度。」由三代陶藝傳人全台語指導拉坯技巧、造型修飾與傳統釉藥塗繪，親手做出獨一無二的台語刻字茶碗！",
            city=CityEnum.NEW_TAIPEI,
            district="鶯歌區",
            category=CategoryEnum.EXPERIENCE,
            start_time="2026-11-01T13:30:00",
            end_time="2026-11-01T16:30:00",
            venue="鶯歌老街陶藝工坊 (新北市鶯歌區尖山埔路)",
            address="新北市鶯歌區尖山埔路68號",
            organizer="鶯歌陶藝創作者協會 / Accupass",
            source_platform=SourcePlatformEnum.ACCUPASS,
            source_url="https://www.accupass.com/event/2611010917221",
            cover_image="https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80",
            price_info="NT$ 650 (含陶土、窯燒代工與郵寄費)",
            is_free=False,
            tags=["台語體驗", "鶯歌陶藝", "手拉坯", "文創手作", "Accupass"]
        ),
        Activity(
            id="accupass_tour_15",
            title="【台語導覽】大溪老街木藝文化巡禮・全台語文史走讀",
            description="走訪大溪和平老街、普濟堂與木藝生態博物館，由在地大溪文史耆老全程台語解說巴洛克牌樓建築、傳統木器雕刻技藝與大溪豆干的百年傳承。",
            city=CityEnum.TAOYUAN,
            district="大溪區",
            category=CategoryEnum.TOUR,
            start_time="2026-11-21T09:30:00",
            end_time="2026-11-21T12:30:00",
            venue="大溪木藝生態博物館 壹號館前",
            address="桃園市大溪區中正路35號",
            organizer="大溪木藝文史工作室 / Accupass",
            source_platform=SourcePlatformEnum.ACCUPASS,
            source_url="https://www.accupass.com/event/2611210839121",
            cover_image="https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80",
            price_info="免費參加 (需事先線上報名 Accupass)",
            is_free=True,
            tags=["台語導覽", "大溪老街", "木藝", "桃園走讀", "Accupass"]
        ),
        Activity(
            id="accupass_exp_17",
            title="【台語體驗】大溪木作童玩手作體驗工作坊（台語教學）",
            description="親手打造傳統台語童玩「竹蜻蜓」與「陀螺（干樂）」！木工老師全程以生動台語介紹台灣木料特性與傳統榫接工藝，做完還能在中庭大玩打干樂競賽！",
            city=CityEnum.TAOYUAN,
            district="大溪區",
            category=CategoryEnum.EXPERIENCE,
            start_time="2026-12-05T14:00:00",
            end_time="2026-12-05T16:30:00",
            venue="大溪工藝基地 (大溪區普濟路)",
            address="桃園市大溪區普濟路13-2號",
            organizer="大溪木藝工坊 / Accupass",
            source_platform=SourcePlatformEnum.ACCUPASS,
            source_url="https://www.accupass.com/event/2612050931201",
            cover_image="https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80",
            price_info="NT$ 380 (含木作材料包與工具借用)",
            is_free=False,
            tags=["台語體驗", "大溪木藝", "童玩手作", "打干樂", "Accupass"]
        ),

        # =========================================================================
        # 7. 社群與日曆 (Facebook, Instagram, Threads, Google Calendar)
        # =========================================================================
        Activity(
            id="fb_story_04",
            title="【台語故事】大稻埕戲苑《囡仔古講堂》：阿公的神秘藏寶圖",
            description="專為 3-10 歲親子家庭設計的台語講古時間！專業台語故事老師結合掌中偶與互動道具，帶領小朋友邊聽故事邊學習生動實用的台語日常詞彙，現場備有精美母語繪本貼紙。",
            city=CityEnum.TAIPEI,
            district="大同區",
            category=CategoryEnum.STORY,
            start_time="2026-09-27T10:30:00",
            end_time="2026-09-27T11:45:00",
            venue="大稻埕戲苑 8樓曲藝場",
            address="臺北市大同區迪化街一段21號8樓",
            organizer="大稻埕戲苑 / 臺北市立社會教育館",
            source_platform=SourcePlatformEnum.FACEBOOK,
            source_url="https://www.facebook.com/dadaochengtheater/events",
            cover_image="https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=80",
            price_info="免費入場（現場自由入座）",
            is_free=True,
            tags=["台語故事", "囡仔古", "大稻埕戲苑", "親子活動", "Facebook"]
        ),
        Activity(
            id="ig_picbook_05",
            title="【台語繪本】信誼親子館《咱來讀繪本》台語親子共讀工作坊",
            description="精選台灣在地原創台語繪本《點心擔》、《暗查查》，透過唱跳童謠、手指謠與台語繪本互動劇，讓家長與孩子在歡笑聲中自然開口講台語！",
            city=CityEnum.TAIPEI,
            district="中正區",
            category=CategoryEnum.PICTURE_BOOK,
            start_time="2026-10-04T14:00:00",
            end_time="2026-10-04T15:30:00",
            venue="信誼小太陽親子館 故事舞台",
            address="臺北市中正區重慶南路二段51號1樓",
            organizer="信誼基金會 / @taigi_picturebooks",
            source_platform=SourcePlatformEnum.INSTAGRAM,
            source_url="https://www.instagram.com/p/DA_taigi_kids_book/",
            cover_image="https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
            price_info="材料費 NT$ 200 (一組一大一小)",
            is_free=False,
            tags=["台語繪本", "信誼親子館", "童謠", "Instagram", "幼兒共讀"]
        ),
        Activity(
            id="threads_tour_07",
            title="【台語導覽】艋舺夜遊：剝皮寮到龍山寺的台語庶民夜市探訪",
            description="Threads 社群人氣走讀發起！夜間漫步萬華青山宮、清水巖祖師廟與剝皮寮歷史街區。聽文史青年用在地腔調台語細說艋舺三大廟宇傳奇與青草巷夜市小吃典故。",
            city=CityEnum.TAIPEI,
            district="萬華區",
            category=CategoryEnum.TOUR,
            start_time="2026-10-16T19:00:00",
            end_time="2026-10-16T21:00:00",
            venue="龍山寺廟埕前集合",
            address="臺北市萬華區廣州街211號",
            organizer="@taigi_walk_night (Threads 揪團)",
            source_platform=SourcePlatformEnum.THREADS,
            source_url="https://www.threads.net/@taigi_walk_night/post/C9x81_nighttour",
            cover_image="https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?auto=format&fit=crop&w=800&q=80",
            price_info="免費參加 (自備耳機導覽機押金100元)",
            is_free=True,
            tags=["台語導覽", "Threads", "艋舺", "龍山寺", "夜間走讀"]
        ),
        Activity(
            id="gcal_play_09",
            title="【台語舞台劇】差事劇團《母語的河流》新北客家與台語跨界劇",
            description="以淡水河流域為歷史背景，融合台語口述歷史、客語歌謠與當代劇場肢體語言，探討土地、移民與語言傳承的生命記憶。",
            city=CityEnum.NEW_TAIPEI,
            district="淡水區",
            category=CategoryEnum.STAGE_PLAY,
            start_time="2026-10-24T19:30:00",
            end_time="2026-10-24T21:15:00",
            venue="淡水雲門劇場 (Cloud Gate Theater)",
            address="新北市淡水區中正路一段6巷36號",
            organizer="差事劇團 / 新北市文化局",
            source_platform=SourcePlatformEnum.GOOGLE_CALENDAR,
            source_url="https://calendar.google.com",
            cover_image="https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?auto=format&fit=crop&w=800&q=80",
            price_info="NT$ 500 ~ 1,200",
            is_free=False,
            tags=["台語舞台劇", "雲門劇場", "淡水", "跨界戲劇", "Google日曆"]
        ),
        Activity(
            id="threads_story_18",
            title="【台語故事】中壢米倉劇場《巷仔內的台語講古暗訪》",
            description="週五夜晚限定的青年台語講古茶會！在老倉庫改建的米倉劇場內，一邊品飲桃園在地東方美人茶，一邊聆聽桃園老火車站與中壢事件的庶民台語記憶。",
            city=CityEnum.TAOYUAN,
            district="中壢區",
            category=CategoryEnum.STORY,
            start_time="2026-12-11T19:30:00",
            end_time="2026-12-11T21:30:00",
            venue="米倉劇場 (桃園市中壢區中美路二段88號)",
            address="桃園市中壢區中美路二段88號",
            organizer="@taoyuan_taigi_crew (Threads 發起)",
            source_platform=SourcePlatformEnum.THREADS,
            source_url="https://www.threads.net/@taoyuan_taigi_crew/post/C9z01_storynight",
            cover_image="https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=80",
            price_info="場地清潔費 NT$ 150 (含冷泡茶)",
            is_free=False,
            tags=["台語故事", "米倉劇場", "中壢", "Threads", "青年講古"]
        )
    ]
